import { useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { events } from '@/data/events';

export default function EventDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const event = events.find((item) => item.id === id); const [joined, setJoined] = useState(event?.joined ?? false);
  if (!event) return <View style={styles.empty}><Text style={styles.emptyTitle}>Event not found</Text><Text style={styles.emptyText}>This event may have been removed or the link is incorrect.</Text><Pressable onPress={() => router.replace('/events')} style={styles.button}><Text style={styles.buttonText}>Go to events</Text></Pressable></View>;
  return <ScrollView contentContainerStyle={styles.screen}><View style={styles.content}><Text style={styles.category}>{event.category.toUpperCase()}</Text><Text style={styles.title}>{event.title}</Text><Text style={styles.description}>{event.description}</Text><View style={styles.info}><Text style={styles.label}>WHEN</Text><Text style={styles.value}>{event.dateTime}</Text><Text style={styles.label}>WHERE</Text><Text style={styles.value}>{event.venue}</Text><Text style={styles.label}>AVAILABILITY</Text><Text style={styles.value}>{event.available} spots available</Text></View><Text style={[styles.status, joined ? styles.joined : styles.open]}>{joined ? 'You are on the attendee list.' : 'You have not joined this event yet.'}</Text><Pressable onPress={() => setJoined((value) => !value)} style={[styles.button, joined && styles.leave]}><Text style={[styles.buttonText, joined && styles.leaveText]}>{joined ? 'Leave Event' : 'Join Event'}</Text></Pressable><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>Go back</Text></Pressable></View></ScrollView>;
}
const styles = StyleSheet.create({ back: { alignItems: 'center', paddingVertical: 16 }, backText: { color: '#2563EB', fontWeight: '800' }, button: { alignItems: 'center', backgroundColor: '#2563EB', borderRadius: 10, marginTop: 20, paddingVertical: 14 }, buttonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' }, category: { color: '#2563EB', fontSize: 12, fontWeight: '800', letterSpacing: 1.2 }, content: { alignSelf: 'center', maxWidth: 620, width: '100%' }, description: { color: '#52667D', fontSize: 16, lineHeight: 24, marginTop: 14 }, empty: { alignItems: 'center', backgroundColor: '#F6F9FC', flex: 1, justifyContent: 'center', padding: 30 }, emptyText: { color: '#62748A', marginTop: 8, textAlign: 'center' }, emptyTitle: { color: '#14243A', fontSize: 24, fontWeight: '800' }, info: { backgroundColor: '#FFFFFF', borderColor: '#DDE7F2', borderRadius: 16, borderWidth: 1, marginTop: 24, padding: 19 }, joined: { backgroundColor: '#DCFCE7', color: '#166534' }, label: { color: '#718196', fontSize: 11, fontWeight: '800', letterSpacing: 1, marginTop: 13 }, leave: { backgroundColor: '#FFFFFF', borderColor: '#F59E0B', borderWidth: 1 }, leaveText: { color: '#B45309' }, open: { backgroundColor: '#E8F0FF', color: '#1D4ED8' }, screen: { backgroundColor: '#F6F9FC', flexGrow: 1, padding: 22, paddingTop: 52 }, status: { borderRadius: 9, fontSize: 14, fontWeight: '700', marginTop: 18, padding: 13 }, title: { color: '#14243A', fontSize: 30, fontWeight: '800', marginTop: 8 }, value: { color: '#1E3048', fontSize: 15, fontWeight: '700', marginTop: 4 } });
