import { useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

export default function ProfileScreen() {
  const [name, setName] = useState('Jhon Dave Ledesma');
  const [email, setEmail] = useState('jhon.ledesma@campus.edu');
  const [message, setMessage] = useState('');
  const save = () => { if (!name.trim()) return setMessage('Full Name is required.'); if (!email.trim()) return setMessage('Email is required.'); if (!/^\S+@\S+\.\S+$/.test(email.trim())) return setMessage('Enter a valid email address.'); setMessage('Profile saved successfully.'); };
  const isSuccess = message === 'Profile saved successfully.';
  return <ScrollView contentContainerStyle={styles.screen} keyboardShouldPersistTaps="handled"><View style={styles.content}><Text style={styles.title}>Your profile</Text><Text style={styles.subtitle}>Keep your EventMate details current.</Text><View style={styles.summary}><Image source={{ uri: 'https://ui-avatars.com/api/?name=JD&background=2563EB&color=fff&size=160' }} style={styles.avatar} /><View><Text style={styles.name}>{name || 'Your name'}</Text><Text style={styles.email}>{email || 'Add your email'}</Text></View></View><View style={styles.form}><Text style={styles.label}>Full Name</Text><TextInput accessibilityLabel="Full Name" autoCapitalize="words" onChangeText={(value) => { setName(value); setMessage(''); }} style={styles.input} value={name} /><Text style={styles.label}>Email</Text><TextInput accessibilityLabel="Email" autoCapitalize="none" keyboardType="email-address" onChangeText={(value) => { setEmail(value); setMessage(''); }} style={styles.input} value={email} />{!!message && <Text style={isSuccess ? styles.success : styles.error}>{message}</Text>}<Pressable onPress={save} style={({ pressed }) => [styles.save, pressed && styles.pressed]}><Text style={styles.saveText}>Save profile</Text></Pressable></View></View></ScrollView>;
}

const styles = StyleSheet.create({
  avatar: { borderRadius: 35, height: 70, width: 70 }, content: { alignSelf: 'center', maxWidth: 620, width: '100%' }, email: { color: '#62748A', fontSize: 13, marginTop: 5 }, error: { color: '#B42318', fontSize: 13, fontWeight: '600', marginTop: 4 }, form: { backgroundColor: '#FFFFFF', borderColor: '#DDE7F2', borderRadius: 16, borderWidth: 1, marginTop: 22, padding: 19 }, input: { backgroundColor: '#F9FBFD', borderColor: '#C9D7E5', borderRadius: 10, borderWidth: 1, color: '#14243A', fontSize: 15, marginBottom: 17, marginTop: 7, paddingHorizontal: 13, paddingVertical: 12 }, label: { color: '#30445D', fontSize: 13, fontWeight: '800' }, name: { color: '#14243A', fontSize: 18, fontWeight: '800' }, pressed: { opacity: 0.72 }, save: { alignItems: 'center', backgroundColor: '#2563EB', borderRadius: 10, marginTop: 18, paddingVertical: 13 }, saveText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' }, screen: { backgroundColor: '#F6F9FC', flexGrow: 1, padding: 22, paddingTop: 56 }, subtitle: { color: '#62748A', fontSize: 14, marginTop: 7 }, success: { color: '#15803D', fontSize: 13, fontWeight: '700', marginTop: 4 }, summary: { alignItems: 'center', backgroundColor: '#E8F0FF', borderRadius: 16, flexDirection: 'row', gap: 15, marginTop: 22, padding: 18 }, title: { color: '#14243A', fontSize: 29, fontWeight: '800' },
});
